name: Helm Chart Package and Publish

on:
  push:
    branches:
      - main

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    container:
      image: alpine/helm:3.12.1
      options: --entrypoint ''

    strategy:
      matrix:
        chart:
          - generic

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        run: |
          helm registry login --username ${{ secrets.HARBOR_PUBLISH_USER }} --password ${{ secrets.HARBOR_PUBLISH_PASSWORD }} https://hub.cloudcops.de

      - name: Package and Push Helm Chart
        run: |
          helm package ./charts/${{ matrix.chart }}
          helm push ${{ matrix.chart }}*.tgz oci://hub.cloudcops.de/${{ github.repository }}
